### ISSUE TITLE
 GLIBC_2.34 not found (required by ./desockmulti.so)

### ISSUE THREAD

**Issue by Filarna** [zyingp/desockmulti#2]
Hi
i have problem with desockmulti that desockmulti.so required GLIBS 2.34 although i have gilbs 2.34 already install on my ubuntu 21.04
and i test it on the 22.04 as well .Same problem

i compiled desockmulti with "arm-linux-gnueabihf" for my devise
and i run httpd with desock as preload and after some debugging this happen.
`sudo qemu-arm-static -g 5555 -L ./var/www/ -E USE_RAW_FORMAT=1 -E LD_PRELOAD=./desockmulti.so ./usr/sbin/httpd`

`./usr/sbin/httpd: /lib/libc.so.6: version 'GLIBC_2.34' not found (required by  ./desockmulti.so)`

**Comment by zyingp** [comment]
I have not done cross-compilation before for desockmulti.so. But, the error message seems due to the use of desock.so but not desockmulti.so? "`... required by /home/xxx/Desktop/preeny/arm-linux-gnueabihf/desock.so`"  Is there any place configurated to use desock.so?
I am sure that desockmulti.so will not compile or load desock.so.

**Comment by Filarna** [comment]
./usr/sbin/httpd: /lib/libc.so.6: version `GLIBC_2.34' not found (required by ./desockmulti.so) 
oh that was problem that i was getting from preeny too 
than i use desockmulti and getting same result

**Comment by Filarna** [comment]
preeny was actually have some desock binary that looks like desockmulti but i test both of  desockmulti and preeny it same result

**Comment by zyingp** [comment]
Ok. That's feabile.
I encoutered such "GLIBC_xx not found" problem before (but not with desockmulti).  Usually it is caused by the mismatch of the Glibc library between the building and running environments (i.e., not the same or compatible Glibc version used). Building the executable with the same Glibc library of the running environment could solve it.

**Comment by Filarna** [comment]
i get proper hardware for the exact architecture of my binary 
problem solved .
thanks.
